sudo: required
services:
    - docker

before_install:
    - docker build -t jipram017/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jipram017/docker-react npm run test -- --coverage